obj-m += st7735fb.o st7735rdr.o  
ccflags-y := -std=gnu99
all:
	$(MAKE) -C  /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	$(MAKE) -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
